### ISSUE TITLE
Gap Detection

### ISSUE THREAD

**Issue by strackoverflow** [strackoverflow/phnx#1]
So uh, there's gap detection logic in place in main-assistant.js (in the gotItems function). Just needs the capability to insert the missing tweets and she's good to go.

**Comment by Fiaxhs** [comment]
I'm trying to implement this.

What behavior should the app have when the gap is huge (let say 100+ tweets). Loading them by pack of 100 ?

**Comment by strackoverflow** [comment]
Yeah ideally it would load 100 tweets and if there was still a gap, it would indicate that

**Comment by Fiaxhs** [comment]
Ok then :)
