### ISSUE TITLE
Instapaper support?

### ISSUE THREAD

**Issue by ivylee** [strackoverflow/phnx#10]
will phnx support instapaper in the future?

**Comment by strackoverflow** [comment]
It's unlikely that the webOS version will see many new features - might merge some stuff from Project Macaw (they've been extending phnx far beyond where I would take it - https://github.com/minego/phnx) but other than that development is mostly maintenance at this point.

**Comment by strackoverflow** [comment]
Oh and sorry for the slow response, I haven't been on GitHub in a few days :)

**Comment by ivylee** [comment]
oh I understand. phnx is a great twitter client on web os nonetheless :)

On Thu, Dec 8, 2011 at 7:12 AM, David Strack <
reply@reply.github.com

**Comment by strackoverflow** [comment]
Thanks :)
