### ISSUE TITLE
Not all new tweets

### ISSUE THREAD

**Issue by DasLampe** [strackoverflow/phnx#9]
When I start the app, after a while, a lot of tweets loaded.

I think it's better, when only the newest 20 where loaded. This speed up the app.

Maybe this feature is optional.

**Comment by strackoverflow** [comment]
Ideally webOS wouldn't slow to a crawl with more than a few hundred elements on the screen but you're right. If gap detection ever gets implemented I will be able to reduce the number of tweets loaded and improve the speed of the app.
